### ISSUE TITLE
No such file or directory: 'config_hawaii.pkl'

### ISSUE THREAD

**Issue by Cuda-Chen** [wayneweiqiang/QuakeFlow#1]
Hi everyone,

I have deploy QuakeFlow on my computer with minikube.
So far so good.

However, when I try to connect to QuakeFlow streamlit dashboard,
I get the following error on browser:
```
$ minikube service streamlit-ui
|-----------|--------------|-------------|---------------------------|
| NAMESPACE |     NAME     | TARGET PORT |            URL            |
|-----------|--------------|-------------|---------------------------|
| default   | streamlit-ui |        8501 | http://192.168.49.2:32348 |
|-----------|--------------|-------------|---------------------------|
🎉  Opening service default/streamlit-ui in default browser...

# in browser
FileNotFoundError: [Errno 2] No such file or directory: 'config_hawaii.pkl'
Traceback:
File "/opt/conda/envs/cs329s/lib/python3.7/site-packages/streamlit/script_runner.py", line 350, in _run_script
    exec(code, module.__dict__)
File "/app/ui_streamlit_iris.py", line 66, in <module>
    with open(CONFIG_PKL, "rb") as fp:
```

I guess I need `config_hawaii.pkl` and `stations_hawaii.csv`.
So are there any suggestions to get these two files (uploaded by maintainer or self-generation)?
Thanks for your help.

**Comment by wayneweiqiang** [comment]
Hi, please try the app_plotly.py inside the UI folder. The streamlit ui is not very stable, so we change to use plotly instead.

**Comment by Cuda-Chen** [comment]
Got it.
I will try to use plotly with kubernetes to view the result.
